server:
  config:
    logLevel: "debug,info,error"

    numHistoryShards: 512

    persistence:
      default:
        driver: "cassandra"

        cassandra:
          hosts: ["10.148.0.15","10.148.0.16","10.148.0.17"]
          port: 9042
          keyspace: temporal
          user: "cassandra"
          password: "cassandra"
          replicationFactor: 3
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

      visibility:
        driver: "cassandra"

        cassandra:
          hosts: ["10.148.0.15",]
          port: 9042
          keyspace: temporal_visibility
          user: "cassandra"
          password: "cassandra"
          replicationFactor: 3
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
