server:
  dynamicConfig:
    matching.numTaskqueueReadPartitions:
    - value: 20
      constraints: {}
    matching.numTaskqueueWritePartitions:
    - value: 20
      constraints: {}
  history.acquireShardConcurrency:
    - constaints: {}
      value: 140