server:
  config:
    logLevel: "debug,info"

    numHistoryShards: 512

    persistence:
      default:
        driver: "cassandra"

        cassandra:
          hosts: ["10.148.0.3", "10.148.0.4", "10.148.0.8"]
          port: 9042
          keyspace: temporal
          user: ""
          password: ""
          existingSecret: ""
          replicationFactor: 3
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

      visibility:
        driver: "cassandra"

        cassandra:
          hosts: ["10.148.0.3", "10.148.0.4", "10.148.0.8"]
          port: 9042
          keyspace: temporal_visibility
          user: ""
          password: ""
          existingSecret: ""
          replicationFactor: 3
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
